In [1]:
import numpy as np

In [62]:
arr1 = np.array([80,65,87,20,40])
print(arr1)

[80 65 87 20 40]


In [38]:
arr2 = np.array([10,20,30,40,50,60,70,75,80,85,90,95])
print()
print(arr2.shape)
print()
print(type(arr2))


(12,)

<class 'numpy.ndarray'>


In [9]:
print(np.__version__)

1.21.5


In [36]:

newarr = arr2.reshape(4, 3)
print(newarr)
print()


print("the shape of the array is:",newarr.shape)
print()

print('the diminstion of the array is:',newarr.ndim)

[[10 20 30]
 [40 50 60]
 [70 75 80]
 [85 90 95]]

the shape of the array is: (4, 3)

the diminstion of the array is: 2


In [27]:

newarr1 = arr2.reshape(2, 3, 2)

print(newarr1)

print("the shape of the array is:",newarr1.shape)
print("the diminstion of the array is:",newarr1.ndim)


[[[10 20]
  [30 40]
  [50 60]]

 [[70 75]
  [80 85]
  [90 95]]]
the shape of the array is: (2, 3, 2)
the diminstion of the array is: 3


In [28]:
print("the date type of the array is:",newarr1.dtype.name)

the date type of the array is: int32


In [21]:
print(newarr1.reshape(3, 4).base)

[10 20 30 40 50 60 70 75 80 85 90 95]


In [37]:
print("the size of the array is",newarr1.size)

the size of the array is 12


In [39]:
arr3 = np.array([[25,87,90],[45,32,57,],[1,5,77],[78,42,17]])
print(arr3)

[[25 87 90]
 [45 32 57]
 [ 1  5 77]
 [78 42 17]]


In [40]:
arr3.shape


(4, 3)

In [41]:
zeroesarr = np.zeros((4,4))
print(zeroesarr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
zeroesarr[3,2] = 10
print(zeroesarr)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. 10.  0.]]


In [43]:
onesarr = np.ones((3,2))
print(onesarr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [46]:
onesarr[0,1] = 3
print(onesarr)

[[1. 3.]
 [1. 1.]
 [1. 1.]]


In [50]:
np.empty((3,4))

array([[4.45057637e-308, 1.78021527e-306, 8.45549797e-307,
        1.37962049e-306],
       [1.11260619e-306, 1.78010255e-306, 1.42409073e-306,
        4.45058910e-308],
       [8.45596650e-307, 9.34602321e-307, 4.94065646e-322,
        3.60282749e+175]])

In [52]:
np.arange(10,95,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94])

In [55]:
print(f'Original Array:\n{arr3}')
print()

arr3_transpose = arr3.transpose()

print(f'Transposed Array:\n{arr3_transpose}')

Original Array:
[[25 87 90]
 [45 32 57]
 [ 1  5 77]
 [78 42 17]]

Transposed Array:
[[25 45  1 78]
 [87 32  5 42]
 [90 57 77 17]]


In [59]:
a = np.linspace(10,95,20)

In [64]:
split_arr = np.array_split(arr1, 3)
print(split_arr)

[array([80, 65]), array([87, 20]), array([40])]


In [65]:
arr = np.concatenate((arr1, arr2))
print(arr)

[80 65 87 20 40 10 20 30 40 50 60 70 75 80 85 90 95]


In [69]:
n = np.array([1,5,7,9])
m = np.array([2,8,6,4])

print((n*m)-n)
print((n-m)+2)

[ 1 35 35 27]
[ 1 -1  3  7]


In [74]:
a = np.array([40,95,56,66,34,73,65,78])
f=a
v=a
v[2] = 15
print(a,f,v)

[40 95 15 66 34 73 65 78] [40 95 15 66 34 73 65 78] [40 95 15 66 34 73 65 78]


In [75]:
d= a.copy()
print(d)

[40 95 15 66 34 73 65 78]


In [76]:
d

array([40, 95, 15, 66, 34, 73, 65, 78])

In [77]:
d[2:5]

array([15, 66, 34])

In [78]:
d[::-1] #reverse


array([78, 65, 73, 34, 66, 15, 95, 40])

In [79]:
b = arr3.copy()
b

array([[25, 87, 90],
       [45, 32, 57],
       [ 1,  5, 77],
       [78, 42, 17]])

In [80]:
b[:,2]

array([90, 57, 77, 17])

In [81]:
b[0,:]

array([25, 87, 90])

In [83]:
b[2,0:2]

array([1, 5])

In [84]:
b[-1,:]

array([78, 42, 17])

In [85]:
b[:,-1]

array([90, 57, 77, 17])

In [86]:
b = b.ravel()
print(b)

[25 87 90 45 32 57  1  5 77 78 42 17]
